# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Gateway.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rGateway.proto\"L\n\x0fTemperatureData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\">\n\nLedControl\x12\x0e\n\x06led_id\x18\x01 \x01(\t\x12\r\n\x05ligar\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"E\n\x0cHumidityData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0f\n\x07umidade\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x62\x06proto3')
)




_TEMPERATUREDATA = _descriptor.Descriptor(
  name='TemperatureData',
  full_name='TemperatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='TemperatureData.sensor_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperatura', full_name='TemperatureData.temperatura', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TemperatureData.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=93,
)


_LEDCONTROL = _descriptor.Descriptor(
  name='LedControl',
  full_name='LedControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='led_id', full_name='LedControl.led_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ligar', full_name='LedControl.ligar', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='LedControl.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=157,
)


_HUMIDITYDATA = _descriptor.Descriptor(
  name='HumidityData',
  full_name='HumidityData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='HumidityData.sensor_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='umidade', full_name='HumidityData.umidade', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='HumidityData.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['TemperatureData'] = _TEMPERATUREDATA
DESCRIPTOR.message_types_by_name['LedControl'] = _LEDCONTROL
DESCRIPTOR.message_types_by_name['HumidityData'] = _HUMIDITYDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureData = _reflection.GeneratedProtocolMessageType('TemperatureData', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATUREDATA,
  __module__ = 'Gateway_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureData)
  ))
_sym_db.RegisterMessage(TemperatureData)

LedControl = _reflection.GeneratedProtocolMessageType('LedControl', (_message.Message,), dict(
  DESCRIPTOR = _LEDCONTROL,
  __module__ = 'Gateway_pb2'
  # @@protoc_insertion_point(class_scope:LedControl)
  ))
_sym_db.RegisterMessage(LedControl)

HumidityData = _reflection.GeneratedProtocolMessageType('HumidityData', (_message.Message,), dict(
  DESCRIPTOR = _HUMIDITYDATA,
  __module__ = 'Gateway_pb2'
  # @@protoc_insertion_point(class_scope:HumidityData)
  ))
_sym_db.RegisterMessage(HumidityData)


# @@protoc_insertion_point(module_scope)
